theme: minima
title: My Homepage
author: Aeril
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Test Homepage for First Week on GitHub

# social links
twitter_username: # DO NOT include the @ character, or else the build will fail!
github_username:  Aeril01 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
